name: thub
recipe: lamp
config:
  webroot: .

services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"

  node:
    type: node:6.11
    globals:
      grunt-cli: 1.2.0

tooling:
  test:
    service: appserver
    cmd: vendor/bin/phpunit --bootstrap test/integration/bootstrap.php --colors=auto ./test

