name: thub
recipe: lamp
config:
  webroot: .
  php: 5.6

services:
  appserver:
    run:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT && php -r 'echo password_hash(\"thub\", PASSWORD_DEFAULT);' > thub.passwd"
      - "cd $LANDO_MOUNT && cp lando.thub_config.php thub_config.php"

  node:
    type: node:6.11
    globals:
      grunt-cli: 1.2.0

tooling:
  test:
    service: appserver
    cmd: vendor/bin/phpunit --bootstrap ./test/integration/bootstrap.php --colors=auto ./test
    description: Run all tests

  e2e:
    service: appserver
    cmd: vendor/bin/phpunit --bootstrap ./test/integration/bootstrap.php --colors=auto ./test/integration
    description: Run integration tests

  unit:
    service: appserver
    cmd: vendor/bin/phpunit --colors=auto ./test/unit
    description: Run unit tests

